### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by jamesrudolph** [AsyncTI4/TI4_map_generator_bot#1270] opened 2023-12-23 12:00 UTC
https://github.com/AsyncTI4/TI4_map_generator_bot/blob/master/src%2Fmain%2Fjava%2Fti4%2FMessageListener.java#L520

Use substringBetween here and then null check the string before using it 

Error here https://discord.com/channels/943410040369479690/1012679443615064104/1188036573380476938

**Comment by ninevra** [comment] 2024-01-10 01:06
Hey, so, i can fix this bug, but also:

This section of code is very hard to read and afaict untested. i suspect it has, if not more bugs of this nature, at least more strange edge cases. Would refactoring and/or adding tests be welcome?

Refactoring of course comes with a fair bit of danger. On the other hand, it looks like part of why this code is hard to read is that people working on previous changes also found it hard to read, so, refactoring might reduce labor & the risk of new bugs going forward.

**Comment by Fingon00** [comment] 2024-01-10 01:24
I dont think this is actually a bug that should be fixed. The cause seems to be a user saying "to[color]" with no message. The effect is no action on the user end and a report to the bot log, both of which seem to be positive results. You dont want the user sending empty messages, and the bot log entry reveals relevant user behavior that can be informative on if this is a common user experience, and in what context the user is experiencing it, which is either infrequent enough to not be worth bothering over or frequent enough to warrant some sort of tailored solution, which can be based off the common context we find from the bot log errors. 

I think many things in the bot could use a refactor, but that this particular area is unlikely to see extensive things built off of it,  is not a particularly important part of the bots function (running the game, this part deals with whispers, which the bot is sort of doing as a side role and should probably not attempt to be an expert at).

**Comment by jamesrudolph** [comment] 2024-01-10 18:34
@ninevra I would say you can just handle the error properly and call it a day. If you see obvious tests you can add without a refactor then cool to add those too.

If we do want to capture user behavior then we should be explicit about it. Catch the error and explicitly state why you're logging it.

Seeing "User attempted a to[color] whisper message with no content" is _a lot_ less concerning than seeing "java.lang.StringIndexOutOfBoundsException: Range [2, -1) out of bounds for length 7"

**Closed** 2024-01-16 16:22 UTC
Labels: bug
